# @package _global_
defaults:
  - ../core/base_create@
  - _self_

dataset: correlated_MEDS_data

paths: 
  input_dir: example_data/${dataset}
  save_path: ${oc.env:BONSAI_PROCESSED_DATA}/${dataset}/outcomes/${hydra:job.config_name}.parquet

splits:
  - train
  - tuning
  - held_out

outcome:
  exclude: # OPTIONAL
    dependence: independent # independent/dependent
    conditions:
      - col: code
        vals: [ D437 ]
      - col: code
        vals: [ D438 ]

  outcome:
    dependence: independent # independent/dependent
    conditions:
      - col: code
        vals: [ DE11 ]

  index:
    type: absolute # absolute/relative/exposure
    absolute_date: # absolute
      year: 2020
      month: 1
      day: 1
    relative_hour_shift: # relative
    dependence: # exposure
    conditions: # exposure

  censor: # ALWAYS RELATIVE TO INDEX
    relative_hour_shift: 8760 # one year of follow-up after index
