defaults: 
  - core/base_train@
  - hardware/cpu@hardware
  - _self_

dataset:
outcome:
pretrain_path:

paths:
  dir: ${oc.env:BONSAI_PROCESSED_DATA}/${dataset}
  train_split: ${paths.dir}/subject_data_train.pt
  val_split: ${paths.dir}/subject_data_tuning.pt
  outcome: ${paths.dir}/outcomes/${outcome}.parquet
  vocabulary: ${paths.dir}/vocabulary.pt
  population: ${paths.dir}/population_full.csv
  ckpt_path: last


data:
  shuffle: true

labels:
  # we will convert outcomes to binary based on whether at least one outcome is in the follow up window
  n_hours_start_include: 1 # start follow up (considering outcomes) time after index date (negative means before)
  n_hours_end_include: null

training:
  batch_size: 32
  accumulate_grad_batches: 1 #previously called effective batch size
  epochs: 10
  learning_rate: 5e-4
  optimizer_epsilon: 1e-6
  sampling_weight_fn: 
    _target_: bonsai.functional.sampling.effective_n_samples
  loss_weight_function: 
    _target_: bonsai.functional.loss.effective_n_samples
  scheduler_warmup_epochs: 0.01 # DOUBLE CHECK THAT THIS IS DESIRED
  ckpt_every_n_epoch: 1
  limit_val_batches: 50
  limit_train_batches: 50
  eval_monitor_metric: val/loss

  #Below is planned for implementation but not yet done
  #checkpoint_frequency: 1
  #early_stopping: 20 # rename this to tell what the value represents
  #stopping_criterion: roc_auc
  #n_layers_to_freeze: 1
  #unfreeze_on_plateau: true # unfreeze all layers if the performance is less than plateau_threshold 
  #unfreeze_at_epoch: 2 # if unfrezze_on_plateau is true, whichever condition is met first
  #plateau_threshold: 0.01 
  #reset_patience_after_unfreeze: true # reset early stopping counter after unfreezing

  # Below is not planned to be implemented
  #info: true
  #gradient_clip: 
  #  clip_value: 1.0

model:
  hidden_size: 64
  num_hidden_layers: 3
  num_attention_heads: 3
  # intermediate_size: 256 # ALWAYS SET THIS TO x4 hidden_size
  max_seqlen: 8192
  causal: false
  bias: false